ALTER TABLE IF EXISTS accounts ADD COLUMN IF NOT EXISTS label VARCHAR(64);
ALTER TABLE IF EXISTS accounts ADD COLUMN IF NOT EXISTS api_key_encrypted TEXT;
ALTER TABLE IF EXISTS accounts ADD COLUMN IF NOT EXISTS api_secret_encrypted TEXT;
ALTER TABLE IF EXISTS accounts ADD COLUMN IF NOT EXISTS api_passphrase_encrypted TEXT;
